backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  
publish_mode: editorial_workflow

media_folder: "static/images/uploads" # Folder where user uploaded files should go
public_folder: "/images/uploads"

collections: # A list of collections the CMS should be able to edit
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Blog" # Used in the UI, ie.: "New Post"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}    
  - name: "settings"
    label: "Settings"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "data/menu.yml"
        fields:
          - label: "Navigation"
            name: navs
            widget: "list"
            fields:
             - {label: Title, name: name, widget: string}
             - {label: URL, name: url, widget: string}
             - {label: Popup, name: popup, widget: string, required: false}
             - {label: Class, name: class, widget: string, required: false}
          - label: "Login Register"
            name: loginRegister
            widget: "list"
            fields:
             - {label: Title, name: name, widget: string}
             - {label: URL, name: url, widget: string}
             - {label: Popup, name: popup, widget: string, required: false}
             - {label: Class, name: class, widget: string, required: false}
      - name: "footer"
        label: "Footer"
        file: "data/footer.yml"
        fields:
          - {label: copyright, name: copyright, widget: string}
          - label: "Footer Top"
            name: footerTop
            widget: "object"
            fields:
             - {label: Heading, name: heading, widget: string}
             - {label: Information, name: info, widget: string}
             - {label: Button Text, name: ButtonText, widget: string, required: false}
             - {label: Button URL, name: ButtonUrl, widget: string, required: false}
          - label: "Footer Bottom"
            name: footerBottom
            widget: "object"
            fields:
             - {label: About, name: about, widget: string}
             - {label: Information, name: info, widget: string}
             - {label: Button Text, name: ButtonText, widget: string, required: false}
             - {label: Button URL, name: ButtonUrl, widget: string, required: false}
          - label: "Footer Navigation"
            name: navs
            widget: "object"
            fields:
            - label: "Working with Brands"
              name: WorkingwithBrands
              widget: "list"
              fields:
               - {label: Title, name: name, widget: string}
               - {label: URL, name: url, widget: string}
               - {label: Popup, name: popup, widget: string, required: false}
               - {label: Class, name: class, widget: string, required: false}
            - label: "Diensten"
              name: Diensten
              widget: "list"
              fields:
               - {label: Title, name: name, widget: string}
               - {label: URL, name: url, widget: string}
               - {label: Popup, name: popup, widget: string, required: false}
               - {label: Class, name: class, widget: string, required: false}
            - label: "Legal"
              name: Legal
              widget: "list"
              fields:
               - {label: Title, name: name, widget: string}
               - {label: URL, name: url, widget: string}
               - {label: Popup, name: popup, widget: string, required: false}
               - {label: Class, name: class, widget: string, required: false}
  - label: "Home"
    name: "home"
    files:
      - label: "Home Feature Area Top"
        name: "featureAreaTop"
        file: "data/featureAreaTop.yml"
        fields:
          - {label: enable, name: enable, widget: string}
          - {label: Title Section, name: titleSection, widget: string}
          - label: "list"
            name: list
            widget: "list"
            fields:
             - {label: image, name: image, widget: image}
             - {label: heading, name: heading, widget: string}
             - {label: info, name: info, widget: string}
      - label: "About"
        name: "about"
        file: "data/about.yml"
        fields:
          - {label: enable, name: enable, widget: string}
          - {label: Title Section, name: titleSection, widget: string}
          - label: "list"
            name: list
            widget: "list"
            fields:
             - {label: image, name: image, widget: image}
             - {label: Title, name: title, widget: string}
             - {label: button Text, name: buttonText, widget: string}
             - {label: button Url , name: buttonUrl, widget: string}             
             - label: "subList"
               name: subList
               widget: "list"
               fields:
                - {label: sublist, name: sublist, widget: string}